window.esdocSearchIndex = [
  [
    "./app/screens/gamescreen.js~gamescreen",
    "class/app/screens/GameScreen.js~GameScreen.html",
    "<span>GameScreen</span> <span class=\"search-result-import-path\">./app/screens/GameScreen.js</span>",
    "class"
  ],
  [
    "./app/screens/gamescreen.js~gamescreencontainer",
    "variable/index.html#static-variable-GameScreenContainer",
    "<span>GameScreenContainer</span> <span class=\"search-result-import-path\">./app/screens/GameScreen.js</span>",
    "variable"
  ],
  [
    "./app/screens/homescreen.js~homescreen",
    "variable/index.html#static-variable-HomeScreen",
    "<span>HomeScreen</span> <span class=\"search-result-import-path\">./app/screens/HomeScreen.js</span>",
    "variable"
  ],
  [
    "./app/screens/homescreen.js~homescreencontainer",
    "variable/index.html#static-variable-HomeScreenContainer",
    "<span>HomeScreenContainer</span> <span class=\"search-result-import-path\">./app/screens/HomeScreen.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~join_game",
    "variable/index.html#static-variable-JOIN_GAME",
    "<span>JOIN_GAME</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~join_random_game",
    "variable/index.html#static-variable-JOIN_RANDOM_GAME",
    "<span>JOIN_RANDOM_GAME</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~send_clue_message",
    "variable/index.html#static-variable-SEND_CLUE_MESSAGE",
    "<span>SEND_CLUE_MESSAGE</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~send_guess_message",
    "variable/index.html#static-variable-SEND_GUESS_MESSAGE",
    "<span>SEND_GUESS_MESSAGE</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~socket_clue_message",
    "variable/index.html#static-variable-SOCKET_CLUE_MESSAGE",
    "<span>SOCKET_CLUE_MESSAGE</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~socket_declare_winner",
    "variable/index.html#static-variable-SOCKET_DECLARE_WINNER",
    "<span>SOCKET_DECLARE_WINNER</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~socket_guess_message",
    "variable/index.html#static-variable-SOCKET_GUESS_MESSAGE",
    "<span>SOCKET_GUESS_MESSAGE</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~socket_player_join_game",
    "variable/index.html#static-variable-SOCKET_PLAYER_JOIN_GAME",
    "<span>SOCKET_PLAYER_JOIN_GAME</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~socket_player_leave_game",
    "variable/index.html#static-variable-SOCKET_PLAYER_LEAVE_GAME",
    "<span>SOCKET_PLAYER_LEAVE_GAME</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/screens/screens.js~screens",
    "variable/index.html#static-variable-Screens",
    "<span>Screens</span> <span class=\"search-result-import-path\">./app/screens/Screens.js</span>",
    "variable"
  ],
  [
    "./app/screens/statsscreen.js~statsscreencontainer",
    "variable/index.html#static-variable-StatsScreenContainer",
    "<span>StatsScreenContainer</span> <span class=\"search-result-import-path\">./app/screens/StatsScreen.js</span>",
    "variable"
  ],
  [
    "./app/action_types/actiontypes.js~update_ui_state",
    "variable/index.html#static-variable-UPDATE_UI_STATE",
    "<span>UPDATE_UI_STATE</span> <span class=\"search-result-import-path\">./app/action_types/actionTypes.js</span>",
    "variable"
  ],
  [
    "./app/actions/user.js~joingame",
    "variable/index.html#static-variable-joinGame",
    "<span>joinGame</span> <span class=\"search-result-import-path\">./app/actions/user.js</span>",
    "variable"
  ],
  [
    "./app/actions/user.js~joinrandomgame",
    "variable/index.html#static-variable-joinRandomGame",
    "<span>joinRandomGame</span> <span class=\"search-result-import-path\">./app/actions/user.js</span>",
    "variable"
  ],
  [
    "./app/actions/dealer.js~submitclue",
    "variable/index.html#static-variable-submitClue",
    "<span>submitClue</span> <span class=\"search-result-import-path\">./app/actions/dealer.js</span>",
    "variable"
  ],
  [
    "./app/actions/user.js~submitguess",
    "variable/index.html#static-variable-submitGuess",
    "<span>submitGuess</span> <span class=\"search-result-import-path\">./app/actions/user.js</span>",
    "variable"
  ],
  [
    "./app/actions/ui.js~updateuistate",
    "variable/index.html#static-variable-updateUIState",
    "<span>updateUIState</span> <span class=\"search-result-import-path\">./app/actions/ui.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "app/action_types/actiontypes.js",
    "file/app/action_types/actionTypes.js.html",
    "app/action_types/actionTypes.js",
    "file"
  ],
  [
    "app/actions/__tests__/dealer.js",
    "file/app/actions/__tests__/dealer.js.html",
    "app/actions/__tests__/dealer.js",
    "file"
  ],
  [
    "app/actions/__tests__/players.js",
    "file/app/actions/__tests__/players.js.html",
    "app/actions/__tests__/players.js",
    "file"
  ],
  [
    "app/actions/__tests__/user.js",
    "file/app/actions/__tests__/user.js.html",
    "app/actions/__tests__/user.js",
    "file"
  ],
  [
    "app/actions/dealer.js",
    "file/app/actions/dealer.js.html",
    "app/actions/dealer.js",
    "file"
  ],
  [
    "app/actions/ui.js",
    "file/app/actions/ui.js.html",
    "app/actions/ui.js",
    "file"
  ],
  [
    "app/actions/user.js",
    "file/app/actions/user.js.html",
    "app/actions/user.js",
    "file"
  ],
  [
    "app/components/chatslist.js",
    "file/app/components/ChatsList.js.html",
    "app/components/ChatsList.js",
    "file"
  ],
  [
    "app/components/playerinput.js",
    "file/app/components/PlayerInput.js.html",
    "app/components/PlayerInput.js",
    "file"
  ],
  [
    "app/components/__tests__/playerinputtest.js",
    "file/app/components/__tests__/PlayerInputTest.js.html",
    "app/components/__tests__/PlayerInputTest.js",
    "file"
  ],
  [
    "app/providers/providers.js",
    "file/app/providers/providers.js.html",
    "app/providers/providers.js",
    "file"
  ],
  [
    "app/reducers/__tests__/combined.js",
    "file/app/reducers/__tests__/combined.js.html",
    "app/reducers/__tests__/combined.js",
    "file"
  ],
  [
    "app/reducers/__tests__/messages.js",
    "file/app/reducers/__tests__/messages.js.html",
    "app/reducers/__tests__/messages.js",
    "file"
  ],
  [
    "app/reducers/__tests__/players.js",
    "file/app/reducers/__tests__/players.js.html",
    "app/reducers/__tests__/players.js",
    "file"
  ],
  [
    "app/reducers/index.js",
    "file/app/reducers/index.js.html",
    "app/reducers/index.js",
    "file"
  ],
  [
    "app/reducers/messages.js",
    "file/app/reducers/messages.js.html",
    "app/reducers/messages.js",
    "file"
  ],
  [
    "app/reducers/players.js",
    "file/app/reducers/players.js.html",
    "app/reducers/players.js",
    "file"
  ],
  [
    "app/reducers/routes.js",
    "file/app/reducers/routes.js.html",
    "app/reducers/routes.js",
    "file"
  ],
  [
    "app/reducers/ui.js",
    "file/app/reducers/ui.js.html",
    "app/reducers/ui.js",
    "file"
  ],
  [
    "app/screens/gamescreen.js",
    "file/app/screens/GameScreen.js.html",
    "app/screens/GameScreen.js",
    "file"
  ],
  [
    "app/screens/homescreen.js",
    "file/app/screens/HomeScreen.js.html",
    "app/screens/HomeScreen.js",
    "file"
  ],
  [
    "app/screens/screens.js",
    "file/app/screens/Screens.js.html",
    "app/screens/Screens.js",
    "file"
  ],
  [
    "app/screens/statsscreen.js",
    "file/app/screens/StatsScreen.js.html",
    "app/screens/StatsScreen.js",
    "file"
  ],
  [
    "app/screens/__tests__/gamescreentest.js",
    "file/app/screens/__tests__/GameScreenTest.js.html",
    "app/screens/__tests__/GameScreenTest.js",
    "file"
  ],
  [
    "app/screens/__tests__/homescreentest.js",
    "file/app/screens/__tests__/HomeScreenTest.js.html",
    "app/screens/__tests__/HomeScreenTest.js",
    "file"
  ],
  [
    "app/screens/__tests__/statsscreentest.js",
    "file/app/screens/__tests__/StatsScreenTest.js.html",
    "app/screens/__tests__/StatsScreenTest.js",
    "file"
  ],
  [
    "app/store/useragent.js",
    "file/app/store/UserAgent.js.html",
    "app/store/UserAgent.js",
    "file"
  ],
  [
    "app/store/configurestore.js",
    "file/app/store/configureStore.js.html",
    "app/store/configureStore.js",
    "file"
  ]
]